### ISSUE TITLE
[Proposal] transform in settings

### ISSUE THREAD

**Issue by ipetrovic11** [moleculerjs/moleculer-db#110]
Currently there are `populate` and `entityValidator` which could be used for similar purpose, but it looks like kind of a hack to use it to transform entities. 

The general idea here is to be able:
1. To transform input object to object like how it should look in DB. Example, user object, it might arrive with `password`, but what we want to save to DB is `salt` and `hash` and not password field. This is possible with `entityValidator`, but this sounds like a hack. - I was able to figure it out by looking into source code of `entityValidator` since it is using .map on array, but it should use .every.

2. To transform output object to something else. Example to remove `hash` and `salt` fields could be achieved by filtering fields, which is cool, but in case we just want to transform it somehow differently its getting hard and using `populate` for it is more like a hack.

---

Proposal is to:
1. Make entityValidator(or just validator) only do validation, and not transforming
2. Add entityTransformer(or just transformer): { in: function, out: function }

Not sure what exactly needs to be done, but can write some proposal.

**Comment by icebob** [comment]
I think you probably misunderstand the populate & entityValidator functionality.
Use `populate` to resolve a foreign key & get data from other service by ID.
Use `entityValidator` to validation (and not transform) the incoming data for `create` & `update` actions.
If you want to transform the incoming data (e.g. hashing password) use the action before hook. IF you want to transform the outgoing data (remove fields or change structure) use the action after hook.

**Comment by ipetrovic11** [comment]
Sorry, I didn't misunderstand, was just looking for alternative/hack :)
---
Thanks, totally forgot about hooks.
Might be valuable to add just one or two sentence about this into docs for moleculer-db.

I can try to help with that.

**Comment by icebob** [comment]
It's true, the documentation doesn't mention that. We will update it.

**Comment by AndreMaz** [comment]
Closing. I've added a [reference](https://moleculer.services/docs/0.13/moleculer-db.html#Data-Manipulation) about hooks in DB's docs

**Comment by ipetrovic11** [comment]
👍
