### ISSUE TITLE
How to update array of object?

### ISSUE THREAD

**Issue by sruthi23** [moleculerjs/moleculer-db#117]
```
ctx.call('user.update', {
   id:2,
  $set: { refreshTokens: ctx.params.token }
})
```
where refreshTokens is an array field. This query is not updating my refreshTokens field.`

**Comment by sruthi23** [comment]
Problem solved by this code:
```
const update = {
    $addToSet: { refreshTokens: ctx.params.token }
 }
this.adapter.updateById({ _id: 2}, update)
```

**Comment by AndreMaz** [comment]
Glad that you've found the solution :smile:  
PS: For questions like this consider using [Discord chat](https://discord.gg/TSEcDRP)
