### ISSUE TITLE
Mongoose adapter missing stringToObjectId / objectIDToString

### ISSUE THREAD

**Issue by wollittech** [moleculerjs/moleculer-db#118]
Setting the `idField` in the schema and calling transformDocuments causes an error in the mongoose adapter because the stringToObjectId / objectIDToString methods are missing.

```
stringToObjectId(id) {
  return new mongoose.Schema.Types.ObjectId(id);
}

protected objectIDToString(id) {
  return id.toString();
}
```

**Comment by AndreMaz** [comment]
Nice catch. Can you create a PR?

**Comment by tobydeh** [comment]
https://github.com/moleculerjs/moleculer-db/pull/119

**Comment by AndreMaz** [comment]
Closing. Solved in https://github.com/moleculerjs/moleculer-db/pull/119
