### ISSUE TITLE
Return pagination data with find (mongoose)

### ISSUE THREAD

**Issue by achabill** [moleculerjs/moleculer-db#121]
Firstly, `find` does not paginate when called with no params even when there are pagination options in settings.

``` 
settings: {

  //https: //moleculer.services/docs/0.13/moleculer-db.html#Settings
  pageSize: 1,
  maxLimit: 1

  //tried these, but no change
  limit: 1,
  offset: 1
 },

...
this.adapter.find(); //returns ALL rows. Expected settings to be considered.
this.adapter.find({limit: 1, offset: 1}); //Works as expected
this.adapter.find({page: 1, pageSize: 1}); //returns ALL rows. 

```

Now, to the main question:

If I don't define a customer `list` action, `service.list` returns with pagination data and uses `pageSize` and `page` for pagination.

e.g 
```
this.broker.call('service.list');

//result
{
  "rows": [....]
  "total": 12,
  "page": 1,
  "pageSize": 2,
  "totalPages": 6
}
```

When I define a custom `list` action, how do I get `this.adapter.find()` to work and return as above instead of just an array?

**Comment by icebob** [comment]
Pagination works in `list` action, If you want to create a custom action with pagination, call the `this._list` method or check the source of `_list`:
https://github.com/moleculerjs/moleculer-db/blob/81919e05a67ac9c973f4743517bcee7a6013aabf/packages/moleculer-db/src/index.js#L738-L759
