### ISSUE TITLE
How to populate nested properties?

### ISSUE THREAD

**Issue by Chank1e** [moleculerjs/moleculer-db#124]
I'd like to populate property which contains inside another property.
My schema is like:
```javascript
const schema = {
  _id: { type: "string", optional: true },
  name: "string",
  values: {
    type: "array",
    items: {
      type: "object",
      props: {
        value: "string",
        category: { type: "string", optional: true }
      },
    },
  },
};

export default schema;

```

I'd like to populate category property. How can I do this? I've tried to populate like `values.items.category`, but it doesn't work

**Comment by icebob** [comment]
This nested populating is not available with moleculer-db. You should make it (e.g. with action hooks)

**Comment by Chank1e** [comment]
> This nested populating is not available with moleculer-db. You should make it (e.g. with action hooks)

Thanks. I've solved this issue with after hook.
