### ISSUE TITLE
Soft Delete Feature

### ISSUE THREAD

**Issue by apriady** [moleculerjs/moleculer-db#125]
I just curious is there anyone else out there that might need this feature?

the idea is if the softdelete setting is set to true and we call remove action instead remove the record, we give a flag to that record to indicate that record is logically deleted.

And when we call list or get, we exclude the record that already flagged as deleted.

**Comment by icebob** [comment]
Yes, it's a good feature, but a next rewritten database service is WIP which will contain it, as well.

**Comment by apriady** [comment]
> Yes, it's a good feature, but a next rewritten database service is WIP which will contain it, as well.

Ah, i see.
Happy to hear if next db service will include this function. 👍 

Currently I must modificate the moleculer-db so that can handle softdelete function to fit what i need. 😄

**Comment by mmiscool** [comment]
I am also interested in a soft delete feature. Any idea when the new version will drop that supports this?

**Comment by icebob** [comment]
https://github.com/moleculerjs/database/tree/master/docs#soft-delete
