### ISSUE TITLE
Sequelize adapter doesn't work correctly when a model instance is passed.

### ISSUE THREAD

**Issue by vadim-shilov** [moleculerjs/moleculer-db#134]
Hi!
For Sequelize v5 the code below doesn't work as expected :(

`let isModelInstance = modelDefinitionOrInstance && Object.prototype.hasOwnProperty.call(modelDefinitionOrInstance, "attributes");`

I guess it should look like this:

`let isModelInstance = modelDefinitionOrInstance && modelDefinitionOrInstance.prototype instanceof Model;`

**Comment by icebob** [comment]
Could you make a fix PR?

**Comment by vadim-shilov** [comment]
Yes, https://github.com/moleculerjs/moleculer-db/pull/141
