### ISSUE TITLE
INSERT autoincrement id get null

### ISSUE THREAD

**Issue by HighSoftWare96** [moleculerjs/moleculer-db#142]
I have created a service that has a model with an autoincrement id as primary key. When I use the INSERT CRUD method the API returns null on every created entity. This issue does not appear in the other methods.
That's the definition of the service:
`  model: {
    name: modelName,
    define: {
      id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        notNull: true
      },
   // ...
`
Calling the insert action returns something like this:
`[
    {
        "id": null,
        "name": "1221",
        "createdAt": "2019-11-07T08:46:46.019Z",
        "updatedAt": "2019-11-07T08:46:46.019Z"
    },
    {
        "id": null,
        "name": "12343",
        "createdAt": "2019-11-07T08:46:46.019Z",
        "updatedAt": "2019-11-07T08:46:46.019Z"
    }
]`

**Comment by icebob** [comment]
could you create a repro example?

**Comment by HighSoftWare96** [comment]
I think this is not possible since there is no way to create a repro with a running server like PostrgreSQL.

**Comment by AndreMaz** [comment]
You can use docker

**Comment by icebob** [comment]
Or using https://www.elephantsql.com/. They have a free plan.

**Comment by icebob** [comment]
By the way, no need a valid a connection string, just leave empty and I will change it in my environment.

**Comment by HighSoftWare96** [comment]
Ok well that's better @icebob thank you!
Here you are: https://codesandbox.io/embed/insert-moleculer-bug-x5o19?fontsize=14
This should be fine with the correct PostgreSQL configuration :)

**Comment by icebob** [comment]
Thanks, great!
So you could reproduce the issue with this code? What is the version of your PostgreSQL?

**Comment by HighSoftWare96** [comment]
Yes, this is the code. I have started the project a week ago so the version are the latest both for molecular and postgresql..

**Comment by icebob** [comment]
I've downloaded the code from codesandbox, `npm i` and it works:
![image](https://user-images.githubusercontent.com/306521/68528535-82ebf900-02f4-11ea-9be5-a734e4bb43fe.png)

**Comment by HighSoftWare96** [comment]
Ok, maybe now it's a bit more detailed than before: https://codesandbox.io/embed/insert-moleculer-bug-x5o19?fontsize=14 this is exactly the code (adapted for company discretion requirements) that generates the issue, or at least it should be. If you're not able to reproduce the issue I'm clearly going to close the issue.

**Comment by icebob** [comment]
It's also work:
![image](https://user-images.githubusercontent.com/306521/68610571-5680da00-04b8-11ea-966b-f5e51b0a0f6d.png)

**Comment by HighSoftWare96** [comment]
Well then I'm sorry, I do not know what's going on on my side. For a more detailed versioning report see this:
```
    "moleculer": "^0.13.9",
    "moleculer-db": "^0.8.2",
    "moleculer-db-adapter-sequelize": "^0.2.2",
    "moleculer-prometheus": "^0.2.4",
    "moleculer-web": "^0.8.5",
    "pg": "^7.12.0",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.12.2",
```

postgresql version: 12

**Comment by HighSoftWare96** [comment]
Actually there is a real issue. I don't know why it is happening on your side but I've found a similar problem in Sequelize with the `bulkCreate` that the `insert` action is using under the hood: like the description in this question https://stackoverflow.com/questions/35079286/sequelize-bulkcreate-returns-null-value-for-primary-key and in the documentation https://sequelize.org/master/manual/instances.html#working-in-bulk--creating--updating-and-destroying-multiple-rows-at-once- the parameter `{returning: true}`
>  will return all columns for each row inserted

So this should be fixed to return all the inserted rows with all the fields compiled. @icebob if you want I can make a small PR :) .
