### ISSUE TITLE
Query object on list action

### ISSUE THREAD

**Issue by jjgumucio** [moleculerjs/moleculer-db#145]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository

## Current Behavior

When the default _list_ endpoint is called with a _query_ parameter, as to perform a filter, moleculer throws an exception saying that the _query_ param must be an object.
The thing is that, when the client makes the call/request, the _query_ object is stringified so it triggers the validation error.

## Expected Behavior

Moleculer _list_ action should accept the stringified _query_ object, transform it into a _POJO_ and pass that object to Mongo.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Make a request to a default moleculer _list_ action like: http://<api-url>/<resource>?query=%7B%22status%22%3A%22not-started%22%7D&order=DESC&page=1&perPage=25&sort=date
2. Moleculer will throw a "ValidationError"

### Context

I am developing a _data provider_ module to use Moleculer as the backend to a [React-Admin](https://marmelab.com/react-admin/) client app. So I need to map the react-admin client requests into Moleculers default REST action endpoints.

* Moleculer version: 0.13
* NodeJS version: 10.15.3
* Operating System: OS X Mojave

Is there a way to get around this?

**Comment by jjgumucio** [comment]
Hey! @icebob I think I found how to fix this:
By just adding the check on _params.query_. If it is a _string_ then we parse it as a POJO.
`
/**
  * Sanitize context parameters at `find` action.
  *
  * @methods
  *
  * @param {Context} ctx
  * @param {Object} params
  * @returns {Object}
  */
sanitizeParams(ctx, params) {
  let p = Object.assign({}, params);

  // Convert from string to number
  if (typeof p.limit === "string") p.limit = Number(p.limit);
  if (typeof p.offset === "string") p.offset = Number(p.offset);
  if (typeof p.page === "string") p.page = Number(p.page);
  if (typeof p.pageSize === "string") p.pageSize = Number(p.pageSize);
  // If query comes stringified from the client, parse it to POJO
  if (typeof p.query === "string") p.query = JSON.parse(p.query);

  if (typeof p.sort === "string")
    p.sort = p.sort.replace(/,/g, " ").split(" ");

  if (typeof p.fields === "string")
    p.fields = p.fields.replace(/,/g, " ").split(" ");

  if (typeof p.populate === "string")
    p.populate = p.populate.replace(/,/g, " ").split(" ");

  if (typeof p.searchFields === "string")
    p.searchFields = p.searchFields.replace(/,/g, " ").split(" ");

  if (ctx.action.name.endsWith(".list")) {
    // Default `pageSize`
    if (!p.pageSize) p.pageSize = this.settings.pageSize;

    // Default `page`
    if (!p.page) p.page = 1;

    // Limit the `pageSize`
    if (
      this.settings.maxPageSize > 0 &&
      p.pageSize > this.settings.maxPageSize
    )
      p.pageSize = this.settings.maxPageSize;

    // Calculate the limit & offset from page & pageSize
    p.limit = p.pageSize;
    p.offset = (p.page - 1) * p.pageSize;
  }
  // Limit the `limit`
  if (this.settings.maxLimit > 0 && p.limit > this.settings.maxLimit)
    p.limit = this.settings.maxLimit;

  return p;
}
`

Please take a look at this and tell me your thoughts.
I can make a pull request if the approach is right.

Cheers!

**Comment by icebob** [comment]
Good idea. Please create a PR, but please add relevant tests as well. Thanks in advance!

**Comment by jjgumucio** [comment]
Should we close this now?

**Comment by icebob** [comment]
Yes

**Comment by azatTemirbek** [comment]
```js
const queryString 		= require("querystring");
...
/**
		 * Split the URL and resolve vars from querystring
		 *
		 * @param {any} req
		 * @returns
		 */
		parseQueryString(req) {
			// Split URL & query params
			let url = req.url;
			let query = {};
			const questionIdx = req.url.indexOf("?", 1);
			if (questionIdx !== -1) {
				query = queryString.parse(req.url.substring(questionIdx + 1));
				url = req.url.substring(0, questionIdx);
			}
			return {query, url};
		},
...
```
iguess this lbrary could be better to solve `query` params so we could user "(acrion.list)?query[active]=true"
result will be params.query = { active : true }
```js
var qs = require('qs');
var assert = require('assert');
assert.deepEqual(qs.parse('foo[bar]=baz'), {
    foo: {
        bar: 'baz'
    }
});
```
