### ISSUE TITLE
Disable default actions

### ISSUE THREAD

**Issue by dwoods** [moleculerjs/moleculer-db#151]
Hi,

I'm using the moleculer-db mixin for most of my data-backed services, but I'd like to disable the default actions for one of the services.  The defaults just don't match up with the way the data is stored in that collection.

I've poked around but I don't see an OOTB way to do this.  What's the best way to accomplish it?

I'm looking for something like this: https://github.com/icebob/kantab/blob/master/backend/services/config.service.js

Thanks!

**Comment by AndreMaz** [comment]
If you want to disable an action just set it to `false`.
More info here: https://moleculer.services/docs/0.13/services.html#Merge-algorithm
