### ISSUE TITLE
query filter in list method is not consider when I use search

### ISSUE THREAD

**Issue by gcareri** [moleculerjs/moleculer-db#153]
Why (in moleculer-db-adapter-sequelize) when I use "search" in list method you don't consider the query parameter?
Example:
{ search: 'gcareri', searchFields: 'name', query: { param1: 1 } }
In this example in the sql query, you don't consider in the where the filter param1 = 1;

In the file moleculer-db-adapter-sequelize/src/index.js, at the row 299, you have:

```
q.where = {
	[Op.or]: fields.map(f => {
                return {
			[f]: {
				[Op.like]: "%" + params.search + "%"
			}
		};
	})
};
```

In my opinion it's better to use this syntax:

```
q.where = _.assign(q.where, {
	[Op.or]: fields.map(f => {
		return {
			[f]: {
				[Op.like]: "%" + params.search + "%"
			}
		};
	})
});
```
What do you think?
Thanks in advice

**Comment by icebob** [comment]
Could you create a PR?

**Comment by gcareri** [comment]
I created it! 
Thanks.
