### ISSUE TITLE
Is there proper guide to create db adapters?

### ISSUE THREAD

**Issue by viralj** [moleculerjs/moleculer-db#154]
I know that there are some developers/contributors trying to work with Cassandra and I am trying to use Moleculer with ScyllaDB. Both databases can be used with datastax's cassandra driver. So is there any guideline that is moleculer db adapter specific that I can use to create adapter for cassandra/scylla?

**Comment by icebob** [comment]
There is no guide, just copy the mongoDB adapter source & write the same methods.

**Comment by viralj** [comment]
Thanks @icebob! I will work on it.
