### ISSUE TITLE
How to remove many records in 1 time ?

### ISSUE THREAD

**Issue by BezMaster** [moleculerjs/moleculer-db#156]
Actualy moleculer-db seems to only have a single remove by Id. Is there a way to delete many records without several call to remove ?

**Comment by icebob** [comment]
The adapter has `removeMany` method, you can expose it as an action.
Pseudo example:
```js
{
    actions: {
        removeAllByCategory(ctx) {
            return this.adapter.removeMany({ category: ctx.params.category });
        }
    }
}
```

**Comment by BezMaster** [comment]
thx a lot ;)
