### ISSUE TITLE
Missing typings for `moleculer-db` packages

### ISSUE THREAD

**Issue by katsanva** [moleculerjs/moleculer-db#17]
Hi @icebob .

I see there is no `d.ts` files in the repo. Also, there are no `@types/*` packages for that.

I've bootstrapped them in my project via [`dts-gen`](https://github.com/Microsoft/dts-gen) but they look not really well.

Will you mind to add them? Or should I create a PR with those crappy `dts-gen` samples?

**Comment by icebob** [comment]
Hi, I'm not a Typescript programmer, so I can't create a proper `d.ts`.

**Comment by katsanva** [comment]
I can try to make that and create a PR
