### ISSUE TITLE
how to alias mixin actions?

### ISSUE THREAD

**Issue by elixiao** [moleculerjs/moleculer-db#170]
I use DbService as a mixin in my service so my service has `find` action now mixed from DbService.  Could I rename `find` to another name such as `dbFind`? Because my service already has a `find` action which has its own logic inside the action and I want to call `dbFind`(the mixin `find`) in my service `find` action. Is it possible? How could I achieve that?

**Comment by icebob** [comment]
The DbServices is a JS object, so you can change what you want before set as a mixin. E.g:

```js
const DbService = require("moleculer-db");

function ChangeActionNames(schema) {
    schema.actions.dbFind = schema.actions.find;
    delete schema.actions.find;
}

module.exports = {
    name: "posts",
    mixins: [ChangeActionNames(DbService)]
}
```

**Comment by elixiao** [comment]
That's exactly what I want. I didn't realize it could be so simple. Thank you very much. @icebob
