### ISSUE TITLE
'get' action returns object with undefined keys

### ISSUE THREAD

**Issue by meehl** [moleculerjs/moleculer-db#173]
If settings.idField is set to a different value other than the default "_id", then calling the 'get' action with 'mapping = true' returns an object with undefined keys. This causes populating not to work properly.

This is the part in the _get() method which returns undefined.
https://github.com/moleculerjs/moleculer-db/blob/34d32375e0955ee4aba96c77843d7324e131a4c0/packages/moleculer-db/src/index.js#L845
I believe this happens because the adapter method afterRetrieveTransformID() isn't called on 'origDoc'.

**Comment by gcareri** [comment]
Hi guys,
I have the same problem.
I solved it with this code:
```
if (_.isArray(json) && params.mapping === true) {
   let res = {};
   json.forEach((doc, i) => {
     const id = origDoc[i][this.settings.idField];
     res[id] = doc;
   });
   return res;
} else if (_.isObject(json) && params.mapping === true) {
  let res = {};
  const id = origDoc[this.settings.idField];
  res[id] = json;
  return res;
}
return json;
```

**Comment by gcareri** [comment]
I did a pull request:
https://github.com/moleculerjs/moleculer-db/pull/176

**Comment by pashist** [comment]
Issue still exists if `settings.idField` is set to a different value other than the default `_id`
