### ISSUE TITLE
Support moleculer-db-adapter-typeorm

### ISSUE THREAD

**Issue by guicovred** [moleculerjs/moleculer-db#194]
Hi, any chance to have [moleculer-db-adapter-typeorm](https://github.com/dkuida/moleculer-db-adapter-typeorm) incorporated to this repository? It has been inactive for a long time and it seems that it is not accepting pull requests. 

As this is the official repository, i think the community could contribute more easily.

Unfortunately, Sequelize not support Oracle and apparently will not do it: https://github.com/sequelize/sequelize/pull/7123#issuecomment-620375692

Therefore, we don't have a good option to use oracle database with moleculerjs. TypeORM would be a good option.

Thanks

**Comment by icebob** [comment]
If you could help to contribute with this repo, I will pull it. But I have no capacity to learn about typeorm and maintain this adapter, as well.

**Comment by guicovred** [comment]
Of course, i would be happy to help!

**Comment by icebob** [comment]
Great. In this case, I will try to reach @dkuida to transfer the repo into moleculer organization. If he doesn't reply, I will fork it and place into it.

**Comment by guicovred** [comment]
Hi, @icebob. Sorry for the inconvenience, but... any news about that?

**Comment by icebob** [comment]
@guicovred Here is the transferred repo: https://github.com/moleculerjs/moleculer-db-adapter-typeorm

**Comment by icebob** [comment]
@guicovred do you still plan to maintain it?

**Comment by guicovred** [comment]
Hi, 

Yes, I consider that the typeorm is an interesting option for the connection with some relational banks so I would like to help to mantain it, unfortunately I'm not having free time for this. At the time of the issue opening, I had a specific need that I ended up solving in another way, so we don’t need to treat this as a priority, if there’s something more interesting to moleculer that I can help with, I’ll be happy to do. Otherwise, in a few months I would look at the typeorm again

**Comment by icebob** [comment]
Ok, go ahead ;)
First of all, try to cover the same functionality as other adapters.

**Comment by riyaz-incredere** [comment]
Hey @icebob @guilhermedalleprane , Is anyone working on this https://github.com/moleculerjs/moleculer-db-adapter-typeorm ? Or any reference to achieve same thing?

**Comment by guilhermedalleprane** [comment]
> Hey @icebob @guilhermedalleprane , Is anyone working on this https://github.com/moleculerjs/moleculer-db-adapter-typeorm ? Or any reference to achieve same thing?

At the time, I ended up not using it, but as far as I know, this module is fully functional, so only some maintenance is done when necessary. If you need something specific, I suggest opening an issue directly in the repository you linked. I'll be happy to help.
