### ISSUE TITLE
Ways to use multiple collections in a db with or without adapters.

### ISSUE THREAD

**Issue by satheesh3** [moleculerjs/moleculer-db#195]
I believe this is an important feature to support. 
`Moleculer follows the one database per service pattern.` - this is good but I cant figure out a way to create multiple collections with in a db.

Ex. scenario: Payments - DB
1. Payment methods - collection
2. Payment transaction - collection.

Note: Yet to be deployed in prod. Someone who already using MolecularJs in Prod could guide me.

**Comment by edud69** [comment]
@satheesh3 Did you find a solution to this?

**Comment by satheesh3** [comment]
@edud69 
I am using MongoDB NodeJs client without molecular adapters.

I have a function with mongodb client connection setup.
db.js
`module.exports = () => {
	const MongoClient = require("mongodb").MongoClient;
	const uri = "mongodb+srv://xxxxxxx/?retryWrites=true&w=majority";
	const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });
	return client;
};`

import above function in the service file.
a.service.js
`
const client = require("../mixins/connect.db")();
async created() {
		client.connect(err => {
			if (!err) {
				client.db("auth").createIndex("users", { email: 1 }, { unique: true });
				client.db("auth").createIndex("users", { phone: 1 }, { unique: true });
				console.log("CONNECTION ESTABLISHED TO MONGODB ATLAS");
			} else {
				console.log("ERROR CONNECTING TO MONGODB ATLAS");
			}
		});
	}`

Use the client to make db operations
`client.db("auth").collection("users").findOne({ phone }, { projection: USER_MASK });`
