### ISSUE TITLE
search behavior in moleculer-db-adapter-mongoose

### ISSUE THREAD

**Issue by guicovred** [moleculerjs/moleculer-db#196]
Hi,
I've noticed that searchFields is not being used in moleculer-db-adapter-mongoose. Comparing the behavior of other adapters and the wiki, seems like this parameter should work to define which fields would be searched, so I would like to suggest an improvement:

When searchFields exists, do a "LIKE" search based on searchFields, when not, uses the full-text search based on index as it is currently. This would not break existing functionality, since without searchFields the search will work as it currently does and will allow the adapter to work like the others when searchFields is informed.

I've already made some adjustments and I believe I have the solution to make this adapter work according to the documentation. I could send a pull request if this behavior is welcome.

**Comment by icebob** [comment]
Great, please send it with a PR. Please don't forget to add relevant tests, as well. Thanks in advance!
