### ISSUE TITLE
feat: allow to specify resulting populated field name

### ISSUE THREAD

**Issue by bzd2000** [moleculerjs/moleculer-db#223]
Hi,

I would like to add this feature that allows to specify the resulting populated field name

```
name: "posts",
		adapter: new Adapter(),
		settings: {
			fields: ["_id", "title", "content", "author","reviewer", "reviewerId"],
			populates: {
				author: {
					action: "users.get"
				},
				reviewerId: {
					field: "reviewer",
					action: "users.get"
				}
			}
		}
```

Instead of replacing reviewerId by the resulting populated object, a new field "reviewer" will be added that contains the populated object.

The reason for this feature is that when replacing the original reviewerId field it breaks the contract towards depending services.
Depending services would expect a field reviewerId which contains the reviewer Id as string.
If the reviewerId field is replace by an object, depending service will break on this.

**Comment by bzd2000** [comment]
@icebob , I'll update the docs, but don't find them

**Comment by AndreMaz** [comment]
@bzd2000 check this: https://moleculer.services/docs/0.14/moleculer-db.html#Populating

the file to edit: https://github.com/moleculerjs/site/blob/master/source/docs/0.14/moleculer-db.md#populating
