### ISSUE TITLE
Mongo DB server not releasing memory after aggregation

### ISSUE THREAD

**Issue by praveencst** [moleculerjs/moleculer-db#236]
I am running MongoDB(v4.2.10) aggregation query in moleculer js(v0.13) application using moleculer-db-adapter-mongo (v0.4.5) and moleculer-db (v0.8.2) my collection has nearly 1000M records and indexed. when i run query in the mongo DB shell it returns result less than one minute and takes 1GB memory from the DB server and release once query execution finished.
when i run the same query from moleculer js app using "moleculer-db-adapter-mongo"  it takes nearly 5 minutes to return the result and take 5GB memory and note releasing the memory once query execution finished.
can someone help me to fix this?

**Comment by icebob** [comment]
moleculer-db is not designed to handle such many records. You should write your methods which use the mongo driver directly and returns with the data.

**Comment by praveencst** [comment]
@icebob  when i run a query i have noticed '{ $limit: 100000 }' is applied to the query which is not purposely added by me is it the upper limit that moleculer-db can handle?

**Comment by icebob** [comment]
moleculer-db doesn't add this limit to the query.
