### ISSUE TITLE
Unused and Wrong imports from mongoose in module [moleculer-db-adapter-mongoose]

### ISSUE THREAD

**Issue by zeeshanalisyed** [moleculerjs/moleculer-db#256]
https://github.com/moleculerjs/moleculer-db/blob/3956f8fee44d4085ae7fc14cf68c6bd2da8b5bb1/packages/moleculer-db-adapter-mongoose/index.d.ts#L4
moleculer-db-adapter-mongoose/index.d.ts:4:3

1. There is no ```ConnectionBase``` in mongoose types file, May be it was in older version of mongoose?
2. If it is not used then Why it is declared here?

#### Supporting Info from vscode ts

- ConnectionBase
```
import ConnectionBase
'ConnectionBase' is declared but its value is never read.ts(6133)
'"mongoose"' has no exported member named 'ConnectionBase'. Did you mean 'CollectionBase'?ts(2724)
```
- DocumentQuery
```
import DocumentQuery
Module '"mongoose"' has no exported member 'DocumentQuery'.ts(2305)
```

**Comment by AndreMaz** [comment]
Hi @zeeshanalisyed the `index.d.ts` for mongoose was last updated in Apr 14, 2018 so it's probably out-of-date. 
Can you please create a PR with updated typings?

**Comment by zeeshanalisyed** [comment]
> Hi @zeeshanalisyed the `index.d.ts` for mongoose was last updated in 2018 so it's probably out-of-date.
> Can you please create a PR with updated typings?

Done, So this issue should be closed already.
