### ISSUE TITLE
Broadcasting the cache clean event is excessive in some scenarios

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer-db#258]
https://github.com/moleculerjs/moleculer-db/blob/3956f8fee44d4085ae7fc14cf68c6bd2da8b5bb1/packages/moleculer-db/src/index.js#L464
Currently the `cache.clean` event is broadcasted to all services in a fan-out manner. I assume the event is broadcasted to ensure any service using a memory cache is properly cleared for all replicas of that service.

This can cause a snow-ball effect in terms of command executions to a service using a shared caching solution for its replicas such as Redis. _As the number of replicas scale for a given service listening to a `cache.clean` event, in-turn the number of executions on the underlying cache will also scale linearly._ This is excessive in the situation where a scaled service is using a shared cache, here only one replica would need to handle the event.

In a situation where you're using an auto-scaling mechanism like _Horizontal pod autoscalers_ in Kubernetes. This could lead to disastrous effects. 

If the service were to scale its replicas as the response times increase, this would cause a linear increase in clean events handled by the scaled service, which in turn would dramatically increase the commands executed on the underlying cache. This could then slow down the response time (if dependent on the cache), causing more replicas, causing more commands. Eventually the cacher will fall-over as the replicas and commands grow. The scan then delete pipeline triggered by a cache.clean is extremely expensive in most caching clients.

**Feature request**
Allow the user to specify via options whether the cache.clean event is fired as a balanced event or a broadcast

**Comment by icebob** [comment]
Good idea. A new `cacheClearEventType: "broadcast" | "emit"` option in the service settings can solve it, right?

**Comment by JordanPawlett** [comment]
Exactly what I had in mind!
I'll try get a PR in this week for this feature, unless anyone else swipes it up first.
In our services it would save us 10s of thousands of messages and cache command executions per seconds, through our bus and caching mechanisms! Unfortunately broadcasting doesn't scale very well, but is sometimes a necessary evil.

**Comment by icebob** [comment]
I did it 👍
