### ISSUE TITLE
missing fields in JSON response

### ISSUE THREAD

**Issue by frozen-eye** [moleculerjs/moleculer-db#264]
missing "page" and improper "totalPages" values
```
{
    "rows": [
        {
            "_id": "APYocsgjCHAA5QHj",
            "name": "admin",
        },
        {
            "_id": "ZPYocsgjCHAA5QHj",
            "name": "admin2",
        }
    ],
    "total": 2,
    "totalPages": null
}

**Comment by icebob** [comment]
When it's missing? How do you call the action?

**Comment by frozen-eye** [comment]
There is a service that uses mixin:

```
module.exports = {
	name: "users",

	/**
	 * Mixins
	 */
	mixins: [DbMixin("users")],
```
and a list action that requires authorization (in fact it overrides the default "list" action provided by dbmixin)
```
/**
	* LIST
	*/
list: {
	auth: "required",
	roles: ["admin"],
	/** @param {Context} ctx  */
	async handler(ctx) {
		const meta = ctx.meta.user;

		if (meta.role === "admin") {
			return await this._list(ctx, { query: { company: meta.company } });
		}
		// an error will be thrown here otherwize..
	}
},
```

**Comment by frozen-eye** [comment]
After the latest code investigation found that only limit is get from settings, all other params should be passed directly (no params are getting into account from this.settings).
Seems like "works as designed". Closing the issue so far.
