### ISSUE TITLE
Update should use dot notation

### ISSUE THREAD

**Issue by felipegcampos** [moleculerjs/moleculer-db#27]
If you have subdocuments and try to update just one property it will remove all properties and add just the updated one.

The correct should be:

`const sets = { 'prop': 'value', 'subdoc.prop1': 'value' }`

**and then**

`this.adapter.updateById(id, { $set: sets })`

Refs:
https://docs.mongodb.com/manual/core/document/#dot-notation
https://www.npmjs.com/package/dot-object

**Comment by icebob** [comment]
Do you have idea, how we can fix it?

**Comment by felipegcampos** [comment]
That's how I am enhancing the update action to work with dot notation:

`handler: async function handler(ctx) {
    const id = this.decodeID(ctx.params.id);
    const sets = dot.dot(omit(ctx.params, ['id']));

    let doc = await this.adapter.updateById(id, { $set: sets });
    if (!doc) {
      throw new MoleculerClientError('Entity not found', 404, null, {
        id,
      });
    }

    doc = await this.transformDocuments(ctx, ctx.params, doc);
    await this.entityChanged('updated', doc, ctx);

    return doc;
  },`

**Comment by Embraser01** [comment]
Hi,

I'm looking at fixing this issue, but I don't know where to put this.
Putting it in the `moleculer-db` project would affect every adapters and may have side effects. 

Putting it in adapters (I was thinking `mongodb` & `mongoose`) would work but logic would be duplicated 🤔 

Any thoughts on this @icebob?

**Comment by icebob** [comment]
@Embraser01 if we put it into `moleculer-db` why is it affect all adapters? I think others don't support  nested properties anyway

**Comment by Embraser01** [comment]
I was thinking about the couchDB Nano adapter which may not handle dot notation the same way as MongoDB but I don't know anything about it.

Adapter like Sequelize don't handle nested properties so I agree it wouldn't affect it
