### ISSUE TITLE
How to call view , Aggrigation , Map reduse  In moleculer DB

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer-db#275]
Hello Guys ,
I need to create views, Aggregation, Map reducers When boot the molecule service  And also need to execute these views,Aggregation ,Map Reduces on In Adeptor . I will try with several method But not Success . If there any method to achieve this 
//	this.adapter.collection.mapReduce()
//     this.adepter.viewname.find()

how can i achive this

**Comment by icebob** [comment]
You have access to the adapter, and to the DB client so you should write them yourself.

**Comment by sachinda123456** [comment]
> You have access to the adapter, and to the DB client so you should write them yourself.

Thanks lot :p

**Comment by sachinda123456** [comment]
> You have access to the adapter, and to the DB client so you should write them yourself.

Do you have sample code ???

**Comment by icebob** [comment]
Which adapter are you using?

**Comment by sachinda123456** [comment]
> Which adapter are you using?

moleculer-db-adapter-mongo

**Comment by icebob** [comment]
In this case, you can reach the MongoClient instance in service via `this.adapter.client`, the database via `this.adapter.db` and the collection via `this.˙adapter.collection`.

So to make aggregation, just call the `this.adapter.collection.aggregate()` inside service actions.

**Comment by sachinda123456** [comment]
Thanks lot . Now i will able to run aggregate with out any error , I have another problem . When i execute aggregate in "NoSql 
Booster for Mongo " It  return  some result set set . But when i console log in  service action It not retrieving   Result data . It log some object . I have attach picture  related to this . Can you able to help me  if there any error ???
	let doc = await this.adapter.collection
					.aggregate()
					.match({ status: true })
					.project({})
					.sort({ _id: -1 })
					.limit(100);

				console.log("documents------>>>>>>>>>>>", doc);
![Screenshot 2021-08-20 at 18 23 08](https://user-images.githubusercontent.com/33275897/130237099-ee3339e7-3552-46e7-a8f2-23504b6a9591.png)
![Screenshot 2021-08-20 at 18 22 11](https://user-images.githubusercontent.com/33275897/130237110-843e45a3-4e4f-4153-89c4-45ac0da975f3.png)
![Screenshot 2021-08-20 at 18 21 46](https://user-images.githubusercontent.com/33275897/130237115-22b75936-403a-479e-9d75-22e9169ff3d4.png)
please help me

**Comment by icebob** [comment]
I've never used Mongo aggrate. Please check help on the internet because it's not a Moleculer specific issue. As I see on the Internet, try to add an `.toArray()` at the end of line.

**Comment by sachinda123456** [comment]
> toArray
Thanks lot . I have fixed issue .i will comment my code below if some one need help

	const pipeline = [
					{
						$match: {
							status: true,
						},
					},
					{
						$group: {
							_id: "$name",
							sumAge: {
								$sum: "$age",
							},
						},
					},
					{
						$sort: {
							name: 1,
						},
					},
					{
						$limit: 100,
					},
				];

				const aggCursor = await this.adapter.collection.aggregate(
					pipeline
				);
				




				return await aggCursor.toArray();
