### ISSUE TITLE
How to get Dynamic Count in adapter.find Query in sequlizer 

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer-db#278]
Hi 
currently i used  "moleculer-db-adapter-sequelize" Adeptor any MySQL Database In Molecular service . I need to know 
I have table called invoice Row in molecular service .  This invoice row table mainly content below fields
-->>invoice_id
-->>quantity
-->>amount
I need to pass specific invoice_id Id and get all rows belong to that invoice . Then i need to (quantity * amount) and calculate sum of those value . If there any way to do my Job In  Adopter find method

**Comment by icebob** [comment]
For calculation you should use RAW queries of sequelize. You can reach the instance as `this.adapter.db`
