### ISSUE TITLE
Populate should accept either an array or a string

### ISSUE THREAD

**Issue by felipegcampos** [moleculerjs/moleculer-db#28]
When I am populating it through the query params I have to add an additional blank attribute to make it an array

`http://[ip]:[port]/users?populate=client&populate=`

Otherwise, it will throw a validation exception.

**Comment by icebob** [comment]
Thanks. Could you make a PR fix? [Here](https://github.com/moleculerjs/moleculer-db/blob/master/packages/moleculer-db/src/index.js#L638) we need to check it is a string with `_.isString`. If yes, convert it to array.

**Comment by felipegcampos** [comment]
I'll do

**Comment by felipegcampos** [comment]
@icebob I don't think it's the problem. The sanitizeParams method should take care of it:

https://github.com/moleculerjs/moleculer-db/blob/bcf1fa5631a7be034be74fb21d4a35358cb08ac1/packages/moleculer-db/src/index.js#L434

I believe the problem is in the params validator:

https://github.com/moleculerjs/moleculer-db/blob/bcf1fa5631a7be034be74fb21d4a35358cb08ac1/packages/moleculer-db/src/index.js#L154

**Comment by felipegcampos** [comment]
I tried to add a new validation to accept both types:

```
populate: [
  { type: "string", optional: true },
  { type: "array", optional: true, items: "string" }
],
```

However, it's failing bc it seems do not accept optional for multi validation.

Any thoughts?

**Comment by AndreMaz** [comment]
I think that this issue was related with #63, which was solved.  So this issue can be closed, right?
