### ISSUE TITLE
Moleculer-db Insert Action

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer-db#280]
In moleculer db default crud operation  There is two default actions . One is create .Other one is insert  . In documentation mention create action create one entity and Insert action create many entities . I need to test default insert action
http://localhost:3000/invoicerow/create
Method:- POST
JSON :- 
  {
        "invoice_id": 1,
        "quantity": -200,
        "amount": 12,
        "currency": 2,
        "description": "aaaaa"
    }
The create action works fine but tried with insert this way

http://localhost:3000/invoicerow/insert
Method :- POST

now return error 

{
    "name": "MoleculerClientError",
    "message": "Invalid request! The 'params' must contain 'entity' or 'entities'!",
    "code": 400
}

How can i solve this

**Comment by icebob** [comment]
To insert one entity, put the content into `entity: {...}` in POST body, to insert multiple, put the content into `entities: [....]` in POST body.
