### ISSUE TITLE
Sending query filter with query string returns 422 - Unprocessable Entity

### ISSUE THREAD

**Issue by felipegcampos** [moleculerjs/moleculer-db#29]
> http://[url]?query={"param1":"value1"}

I am trying to list using the query string to send a query filter but it's returning 422 - Unprocessable Entity

**Comment by icebob** [comment]
you can't use JSON is query params. Try as `http://[url]?query.param1=value1`

**Comment by felipegcampos** [comment]
It's not filtering though it's not throwing any errors now.

**Comment by ptapplied** [comment]
Is there an answer to this?

**Comment by rulrok** [comment]
you can preprocess it in a variable to assign as a query parameter.

```js
const q = encodeURIComponent(JSON.stringify({param1: "value1"}));
const url = `http://${url}?query=${q}`;
```
