### ISSUE TITLE
When will Mongoose 6 be supported?

### ISSUE THREAD

**Issue by lol1pop** [moleculerjs/moleculer-db#295]
I was trying to use the moleculer-db-adapter-mongoose with a newer version of the mongoose ^6.0.12.

in the end I get this error: 

> [Runner] __useNewUrlParser is an invalid option.__ Error: useNewUrlParser is an invalid option. 

as I understand it, the error lies in the library files

>  path: node_modules/moleculer-db-adapter-mongoose/src/index.js
>[ :14:39 , :15:41, :16:38 ]
>```javascript
>mongoose.set("useNewUrlParser", true);
>mongoose.set("useFindAndModify", false);
>mongoose.set("useCreateIndex", true);
>```

**Comment by dalmatele** [comment]
Yes, the same question. I got this error and can not understand what happens with my code until seeing your post :D

**Comment by icebob** [comment]
It's released in 0.9.0
