### ISSUE TITLE
How to prevent rest configuration ?

### ISSUE THREAD

**Issue by swkim0572** [moleculerjs/moleculer-db#308]
I use moleculer-web autoAliases
It registers all rest configuration to router.
Moleculer-db's actions use rest configuration.
But I don't want route moleculer-db automatically.
When routing molecule-db, it is individually authorized using middleware.

**Comment by icebob** [comment]
```js
module.exports = {
  mixins: [DbMixin],

  actions: {
    find: { rest: false },
    count: { rest: false },
    list: { rest: false },
    create: { rest: false },
    get: { rest: false },
    update: { rest: false },
    remove: { rest: false },
  }
}
```
