### ISSUE TITLE
Warning: A promise was created but not returned from it

### ISSUE THREAD

**Issue by mbaertschi** [moleculerjs/moleculer-db#33]
Hi

On line [x498](https://github.com/moleculerjs/moleculer-db/blob/bcf1fa5631a7be034be74fb21d4a35358cb08ac1/packages/moleculer-db/src/index.js#L498) in your moleculer-db/src/index.js file you do not return from the promise in case the if statement fails. Could you please add the following:
```javascript
if (this.schema[eventName] != null) {
  return this.schema[eventName].call(this, json, ctx);
}
return; // <--- this
```

so that we do not get the warnings? 

Thanks and best,
Michael

**Comment by icebob** [comment]
Hi,

I don't think so, because the `entityChanged` function returns a Promise. I think the non-returned promise is in the function what the 496th line called, in an entity changed event handler.

**Comment by mbaertschi** [comment]
Hi @icebob 

Of course you are right! Sorry for bothering you.

Keep on with the great work :-)

Best
