### ISSUE TITLE
[SECURITY] automatically created molecular-db actions can't be authenticated 

### ISSUE THREAD

**Issue by Haiz14** [moleculerjs/moleculer-db#353]
```js
/**
* The "moleculer-db" mixin registers the following actions:
*  - list
*  - find
* - count
*  - create
*  - insert
*  - update
*  - remove
*/
```

These methods that molecular db registers automatically can't be authorised, and anyone can  list all the data in the database.

**Comment by ColinFrick** [comment]
See #174 #303

**Comment by Haiz14** [comment]
Thanks a lot, i should learn how to search issues before posting them. Sorry then.
