### ISSUE TITLE
Bluebird library for promise management shouldn't be used anymore

### ISSUE THREAD

**Issue by Freezystem** [moleculerjs/moleculer-db#356]
As the [bluebird github repo states](https://github.com/petkaantonov/bluebird/#%EF%B8%8Fnote%EF%B8%8F), bluebird shouldn't be used anymore.  
Moreover, the library hasn't got any release since december 2019.  

Promises are available in nodeJS since `v0.12.0` and the minimum version moleculer supports is nodeJS `v8.x.x` so this should be safe regarding backward compatibility issues.  

We eventually could keep it as devDependency for tests purpose but resort to using native promise in adapters.  

I'm willing to make the related PR if it's something that you think should be done.

**Comment by icebob** [comment]
Good idea, a PR would be good, thanks!

**Comment by esatterwhite** [comment]
I think in most cases you don't need to use promises directly anymore except in edge cases. An async function returns a promise inherently.

**Comment by Freezystem** [comment]
Here are the related PRs:
 - #386 
 - #387 
 - #390 
 - #391 
 - #392 
 - #393 
 
To avoid changing the code too much I just removed bluebird but still use `Promise`.
