### ISSUE TITLE
[Mongoose adapter] Error in the log when starting two or more services

### ISSUE THREAD

**Issue by safer-bwd** [moleculerjs/moleculer-db#361]
Error in the log when starting two or more services (if services use one connection).

Packages:
```
"moleculer": "0.14.29",
"moleculer-db": "0.8.23",
"moleculer-db-adapter-mongoose": "0.9.2",
"mongoose": "6.11.3"
```
Example:
```js
const { ServiceBroker } = require('moleculer');
const DbService = require('moleculer-db');
const MongooseAdapter = require('moleculer-db-adapter-mongoose');
const mongoose = require('mongoose');

const MONGO_URI = 'mongodb://localhost:27017/test'

const serviceA = {
  name: 'A',
  mixins: [DbService],
  adapter: new MongooseAdapter(MONGO_URI),
  model: mongoose.model('A', new mongoose.Schema({})),
};

const serviceB = {
  name: 'B',
  mixins: [DbService],
  adapter: new MongooseAdapter(MONGO_URI),
  model: mongoose.model('B', new mongoose.Schema({})),
};

const broker = new ServiceBroker();
broker.createService(serviceA);
broker.createService(serviceB);

broker
  .start()
  .delay(5 * 1000)
  .then(() => broker.stop())
  .catch((err) => console.log('Error', err));
```

Log:
![mongoose1](https://github.com/moleculerjs/moleculer-db/assets/35757462/d537cedc-0fdf-45c7-8250-e5b405cdea1c)
![mongoose2](https://github.com/moleculerjs/moleculer-db/assets/35757462/21c0f6f7-5cdb-422d-bf6f-d1befb125dc7)

Bugs:
- Service B instead of waiting for the connection throws an exception and starts reconnecting;
- Service B does not write a successful connection message to the log.

**Comment by icebob** [comment]
Yeah, I faced the same issue today. This [PR](https://github.com/moleculerjs/moleculer-db/pull/324) implemented this logic which checks the state of the connection. ping @devalexandre

**Comment by thib3113** [comment]
@safer-bwd I fix it on my setup, trying to reproduce what you tell ( start multiple services using moleculer-db-mongoose ) . 

Can you try the changes ? if it fix your setup too ?

**Comment by safer-bwd** [comment]
> @safer-bwd I fix it on my setup, trying to reproduce what you tell ( start multiple services using moleculer-db-mongoose ) .
> 
> Can you try the changes ? if it fix your setup too ?

@thib3113 Works for my case!

![moleculer-mongoose](https://github.com/moleculerjs/moleculer-db/assets/35757462/a4ea6ecf-1b5f-4df6-95fb-ad7748fa3be3)

But I think using mongoose's internal (private?) options is not a good idea.
`conn = mongoose.connection.$initialConnection;`

**Comment by thib3113** [comment]
@safer-bwd in fact, I doesn't find a "clean" way to do it ... 

Else, I need to check with on('connected'), and disable the listener when called (seems to doesn't implement `once` ) https://mongoosejs.com/docs/connections.html#connection-events / or to recall "connect" with the current parameters ? but not sure if it's a good idea ? ( what happen if different url is passed ? )

If I correctly remember $initialConnection is the Promise output from connect . so, we can easily wait on it
