### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by westtrade** [moleculerjs/moleculer-db#363]
https://github.com/moleculerjs/moleculer-db/blob/4b3227bd717d4fafddee3f1f242be65b526d7331/packages/moleculer-db/src/index.js#L926C22-L926C25

Isn't calling the same event beforENtityCHaged('create') on lines 926 and 928 redundant? 

![image](https://github.com/moleculerjs/moleculer-db/assets/13632738/af5c0e42-649a-48f4-9cd9-9ae3f1e85de4)

**Comment by icebob** [comment]
Nice catch
