### ISSUE TITLE
Irrelevant fields are not removed during creation

### ISSUE THREAD

**Issue by westtrade** [moleculerjs/moleculer-db#364]
If we define ` 'id', title', 'content',` in settings fields, and then create post with next content

```
{
title: "Test",
content: "Some test",
evilField: "Azaza"
}
```
field ```evilField``` doesn't omited when doc was created

**Comment by icebob** [comment]
Moleculer uses fastest-validator, for this purpose, you should use `$$strict` feature of the validator.

https://github.com/icebob/fastest-validator#strict-validation
