### ISSUE TITLE
Are you really designed it like - table per service))?

### ISSUE THREAD

**Issue by maksspace** [moleculerjs/moleculer-db#57]

**Comment by ccampanale** [comment]
It would appear that, in it's current state, this adapter only supports a single model. I can definitely work around this myself but I do think it would be nice if the adapter could support multiple models.

A single microservice can maintain multiple models for a single entity so long as they are within the bounded context of that entity's service. For instance, a **user** service may have a model for `User`, `UserPreferences`, `UserPermissions`, `UserNotifications`, etc. Depending on your domain, you may design some of these "principals" to be managed external to the user service when they have broader implications (for instance, notifications), but this approach is also not uncommon.

From a DDD perspective, a single service supporting **users** and providing the domain with the means for a concrete `user` is fine, but it is also - at least in my opinion - an over simplification at the 10k ft level and deserves a closer look. Looking closer, the ability for a single service with it's own DB to support multiple models - or tables as the OP states - is acceptable and I think warranted.
