### ISSUE TITLE
How to handle Reconnecting loop?

### ISSUE THREAD

**Issue by kevmt** [moleculerjs/moleculer-db#58]
Hi, i am using the sequelize adapter and when I was testing invalid connection option, the broker calls the `started()` from the service DbService and does not stop, and if I create a DbService that merges and overrides the `started` func and when I trigger a reject for n count of attempts the broker stops. 

How do I handle such infinite loop `connecting` to resolve? and does returning a reject does not trigger circuit breaker? or maybe can a broker stop loading that service and not halt everything and saying cant load all services.

**Comment by icebob** [comment]
The solution was `adapter: new MongoDbAdapter("mongodb://....", { autoReconnect: false })`
Because MongoDB Client has an internal reconnecting logic.

**Comment by kevmt** [comment]
Hi @icebob I was using it with mysql. I override/overload some functions. https://gist.github.com/kevmt/a524451eb6b6943728926fe9b191bea5
