### ISSUE TITLE
Moleculer with Cassandra

### ISSUE THREAD

**Issue by cuongnl-pnc** [moleculerjs/moleculer-db#60]
Hi,
I'm new in Moleculer. I want to build my project with Moleculer and Cassandra. 
Is there any examples to create a DB Service which connect to Cassandra?
Thank you.

**Comment by icebob** [comment]
Hi,

unfortunately, there is no Cassandra example.

**Comment by cuongnl-pnc** [comment]
Hope Moleculer to have db-adapter supported for other NOSQL databases (eg: Cassandra, Neo4j...) in the future.
Thanks

**Comment by saeedtabrizi** [comment]
hi @cuongnl-pnc 
there is orientdb adapter in dbservice module list .
