### ISSUE TITLE
Setting `idField`is not working properly

### ISSUE THREAD

**Issue by AndreMaz** [moleculerjs/moleculer-db#61]
The setting `idField`is not working properly.

**Steps to reproduce**
```javascript
'use strict'

const { ServiceBroker } = require('moleculer')
const DbService = require('moleculer-db')

const broker = new ServiceBroker()

// Create a DB service for `user` entities
broker.createService({
  name: 'users',
  mixins: [DbService],

  settings: {
    idField: 'myCustomIDField'
  }
})

let newEntry = {
  myCustomIDField: '123456789',
  username: 'john',
  name: 'John Doe',
  status: 1
}

broker.start()
  .then(() => broker.call('users.create', { ...newEntry }))
  .then(() => broker.call('users.find', {}))
  .then(res => console.log(res))
```
**Exptected Result**
```JSON
[ { "username": "john",
    "name": "John Doe",
    "status": 1,
    "myCustomIDField": "123456789'"} ]
```
**Actual Result**
```JSON
[ { "myCustomIDField": "123456789",
    "username": "john",
    "name": "John Doe",
    "status": 1,
    "_id": "ch1O9ghyjFYStlpW" } ]
```
**Problem Location**
In `actions.create` the entity is inserted without checking if it has any `idField` as ID
https://github.com/moleculerjs/moleculer-db/blob/0abed0ee06e2e667bc0ed837ba89a9b1b60867a5/packages/moleculer-db/src/index.js#L207-L212

In `methods.transformDocuments` the `_id` field is not transformed into the `idField`
https://github.com/moleculerjs/moleculer-db/blob/0abed0ee06e2e667bc0ed837ba89a9b1b60867a5/packages/moleculer-db/src/index.js#L537-L541

**Comment by AndreMaz** [comment]
@icebob you've mentioned that you are working on new `moleculer-db`. So my question is: Is this issue already solved in new db module?

**Comment by icebob** [comment]
Yes, in the new module it will be fixed, but I don't know when I will able to make a release, so thanks for the PR!
