### ISSUE TITLE
moleculer-db + moleculer-web

### ISSUE THREAD

**Issue by katsanva** [moleculerjs/moleculer-db#63]
Hi. I've encountered an issue when using `fields` param through `moleculer-web`s query: it seems it's not possible to pass only one field into `fields` - that leads to an error 

```
{
    "name": "ValidationError",
    "message": "Parameters validation error!",
    "code": 422,
    "type": "VALIDATION_ERROR",
    "data": [
        {
            "type": "array",
            "field": "fields",
            "message": "The 'fields' field must be an array!"
        }
    ]
}
```

To avoid that client can use something like `http://my.host/endpoint?fields=foo&fields`
but that doesn't look right.

That is caused by the fact that [fields are defined as array](https://github.com/moleculerjs/moleculer-db/blob/0abed0ee06e2e667bc0ed837ba89a9b1b60867a5/packages/moleculer-db/src/index.js#L81) and how the [qs is parsing the query string](https://github.com/moleculerjs/moleculer-web/blob/d0d9450e156fb05f0d791d5bc593a15f9b93c743/src/index.js#L757).

Any thoughts on that?

**Comment by icebob** [comment]
Yes, it's a defect because when it was made, validator can't handle multiple types (string & array). I will fix it.

**Comment by HighSoftWare96** [comment]
I have a similar issue, when defining a parameter like this:
```javascript
// ...
params: {
  include: {
    type: 'array',
    items: 'string',
    min: 0,
    max: 2,
    optional: true
  }
}
```
and passing (in query string, for example) a single item inside `include`, like this:
`GET entites?include=string`
the framework gets this error:
```javascript
{
  "name": "ValidationError",
  "message": "Parameters validation error!",
  "code": 422,
  "type": "VALIDATION_ERROR",
  "data": [
    {
      "type": "array",
      "field": "include",
      "message": "The 'include' field must be an array!"
    }
  ]
}
```
There is no way to pass a single item in an array parameter? Or have I to define the parameter differently?

**Comment by icebob** [comment]
```js
params: {
  include: [
	  {
		type: 'string'
	  },
	  {
		type: 'array',
		items: 'string',
		min: 0,
		max: 2,
		optional: true
	  }
	]
}
```
