### ISSUE TITLE
Mongoose Adapter / Timeout on unique duplicate.

### ISSUE THREAD

**Issue by Hexenon** [moleculerjs/moleculer-db#79]
I have this problem, i ran my microservices ecosystem with mongo-db-mongoose-adapter and, whenever i try to save a document with an existent unique key, it logs an error, but the api never responds.

<img width="1499" alt="captura de pantalla 2019-03-04 a la s 2 46 45" src="https://user-images.githubusercontent.com/5114683/53724755-d2a22880-3e27-11e9-8ad5-107165035a7f.png">

is there a way to catch it ?.

**Comment by icebob** [comment]
This PR will fix it: https://github.com/moleculerjs/moleculer-web/pull/103

**Comment by Hexenon** [comment]
which version should i install ?.
