### ISSUE TITLE
Api Mixin / possible Enhancement - Style responses before send 

### ISSUE THREAD

**Issue by Hexenon** [moleculerjs/moleculer-db#80]
I was looking a way to style responses before send em back thru api-gateway, but still have not found how.

Is it a hidden feature over there? or should it be a new GREAT feature?-

**Comment by molobala** [comment]
Use hooks.
There are before and after hook, use can stylize your responses there

**Comment by icebob** [comment]
Or use `onAfterCall` route hook: https://moleculer.services/docs/0.12/moleculer-web.html#Route-hooks

**Comment by Hexenon** [comment]
yeah thanks, im looking after it.
