### ISSUE TITLE
global broker / when i start my project with runner

### ISSUE THREAD

**Issue by Hexenon** [moleculerjs/moleculer-db#81]
i was looking a way to get a global broker to use it in Model pre/post hooks, after i ran the project with the moleculer-runner which is the recommended way to do it so. I have not found how to get to the broker, since when i create a new one it cant see the other nodes even with the same namespace and transport.

is there a way?.

**Comment by icebob** [comment]
The only way is to put the broker into global variable in `created` lifecycle.

```js
// moleculer.config.js
module.exports = {
  // ...
  created(broker) {
    global.broker = broker;
  }
}
```

**Comment by Hexenon** [comment]
Thanks!
