### ISSUE TITLE
Import model from model folder

### ISSUE THREAD

**Issue by reticulan** [moleculerjs/moleculer-db#83]
With node and sequelize a can define all my models in another folder in different files and it's extremely comfortable. 
Could I import my model.js and use it in service.js file? like model: myModel ? How to do it? I don't want to keep my models and logic in one trash file.

**Comment by icebob** [comment]
Yes of course. Just import with `require` your model and set it to the service schema.

**Comment by apriady** [comment]
when using mongoose adapter, i do like this 

**models/user.model.js**
```js
const mongoose = require('mongoose');

const UsersSchema = mongoose.Schema(
  {
    name: { type: String },
  }
);

module.exports = mongoose.model('Users', UsersSchema);
```

**services/user.service.js**
```js
const DbService = require('moleculer-db');
const MongooseAdapter = require('moleculer-db-adapter-mongoose');
const UserModel = require('../models/users.model');

module.exports = {
  name: 'users',
  mixins: [DbService],
  adapter: new MongooseAdapter('mongodb://localhost/database'),
  model: UserModel,
}

```
