### ISSUE TITLE
"populateDocs" function incorrectly validates "docs" parameter type

### ISSUE THREAD

**Issue by ricardocoelho22** [moleculerjs/moleculer-db#88]
In src/index.js, the `populateDocs(ctx, docs, populateFields)` function validates the docs parameter using:
`if (docs == null || !_.isObject(docs) || !Array.isArray(docs))`

This makes it so that docs must be an Array, not accepting docs as an Object.
I believe the correct validation should be something like:
`if (docs == null || !_.isObject(docs) && !Array.isArray(docs))`

**Comment by icebob** [comment]
You are right, nice catch. Could you create a fix PR?

**Comment by ricardocoelho22** [comment]
Done in #89

**Comment by icebob** [comment]
Released in 0.7.9
