### ISSUE TITLE
How to populate by default?

### ISSUE THREAD

**Issue by ttrubel** [moleculerjs/moleculer-db#95]
Hello,

can I populate without explicit set populate in find, list and get actions?

Populate fields already in settings, i want to populate this fields by default.

**Comment by aliazlan4** [comment]
The field names present in "fields" array will be populated by default.

**Comment by ttrubel** [comment]
@aliazlan4 unfortunately doesn't works

solved using before hook

```
  hooks: {
    before: {
      "*": (ctx: Context) => {
        ctx.params.populate = "variants,labels";
      },
    },
  },
```
